language: pl
timeout: 25
envs:
  production:
    url: https://inpost.pl/SzybkieNadania/
    env: PRODUCTION
    active: false
  test:
    url: https://test-oneclick-pl.easypack24.net/SzybkieNadania/
    env: TEST
    active: true
  check:
    url: null
    env: CHECK
    active: false