- name: Test Reporter
  # You may pin to the exact commit or the version.
  # uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1
  uses: dorny/test-reporter@v1.5.0
  with:
    # Name or regex of artifact containing test results
    artifact: # optional
    # Name of the check run
    name: 
    # Coma separated list of paths to test resultsSupports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)All matched result files must be of same format

    path: 

    path-replace-backslashes: # optional, default is false

    reporter: java-junit
    # Limits which test suites are listed. Supported options:

    list-suites: # default is all
    
    list-tests: # default is all

    max-annotations: # default is 10
    # Set this action as failed if test report contain any failed test
    fail-on-error: # default is true
    # Relative path under $GITHUB_WORKSPACE where the repository was checked out
    working-directory: # optional
    # Allows you to generate only the summary.

    only-summary: # optional, default is false
    # GitHub Access Token
    token: # optional, default is ${{ github.token }}
